language: python

dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install: make init

script: make ci

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: vnHFaOrwEL2bFtsp9p4rQagEQM/+87stEnEzk9wUtVrzka7ot+vAmXgZgkciWDEZSfl3psmn9CDJbejdXHLSvpfU7IGORf7VZAGl9DRWDIcMrRHsYjXhqNQC4c0BYqypit6HtawjoYbLToaT1BAeT1Cjfe9aKjTRV7fGBg4phOtXn+7r1L818gEx+/2rDQHsddZa3bELc/bWplyTDHu6UVAoeUv7+P2b7lVcPB/es8xToULBa8CAYjxhXh9k9+fbZ1h/jmxKVtuj+J2N8a7OPEwCVISVT4NyBFe6rjkfQPEdhil7ev28cCbJZnWdaK2Fi5pK7ZgylG06UyCqjksbY+koVwjMI2RlVUcp5ZGa137UjS4DlnaaS9tgvOQ89aYZDhit150EnfJutA94ykNAvC6eYfgdIUWVRjs8aa/HYtsGgeoNMAktGt+VUjT+vzu8QErEuU5H6ET68TxwKnB7QVLX26h7cYtptQaI6bONUMPsjfxyzI4tHhP32mQMFiihIi6USnDyiVkG2OqmDMzlXx/Oc4TobrbQ9PQBwVBSeOIisPiWAurTftc2GczDBDG7zCzNHzJQXVURg6JtWWgUn8tx0CWU3chz4QOuHCSEfmdNGpj/F9E4N7g/yFDqr/UVCZd9SA6cc26hSPXHYmCLMi66L3jTPfM+UhU4Td9jP6I=
